[package]
name = "dice_roller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
rand_mt = "4.0.0"
rand = "0.8.5"
serde = "1.0.197"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.getrandom]
version = "0.2.12"
features = ["js"]
