import './styles/global.css'
import { Noto_Serif, Alice } from 'next/font/google'

const notoSerif = Noto_Serif({
  weight: ['400', '700'],
  subsets: ['latin'],
})

const alice = Alice({
  weight: ['400'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Nove Círculos - Mesa',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={alice.className + ' ' + notoSerif.className}>
        {children}
      </body>
    </html>
  )
}
